[[HSL]]
arch = "aarch64"
git-tree-sha1 = "153e1fbba1e10e394a703a10a87578b6747ae00e"
libgfortran_version = "5.0.0"
os = "macos"

    [[HSL.download]]
    sha256 = "34eedc7fa6e3cc0a5995053bfb23cb1af6465be72e9b27c08b7f7c499915bcd7"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.aarch64-apple-darwin-libgfortran5.tar.gz"
[[HSL]]
arch = "aarch64"
git-tree-sha1 = "70547955a0f32eb1160b2d12d37fb73afc6e6502"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "50749615eb3dc93bc2733821d6805ee9ed66411a498c873017beba35b881bac0"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.aarch64-linux-gnu-libgfortran3.tar.gz"
[[HSL]]
arch = "aarch64"
git-tree-sha1 = "88a13f7b4e54f9d62d06a233b04c9395dbb4ada4"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "2ba1ea44cd1cec85536653b0599dcedc19ef207dc7a3c56d6542f37773091db8"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.aarch64-linux-gnu-libgfortran4.tar.gz"
[[HSL]]
arch = "aarch64"
git-tree-sha1 = "561a4630667513bbd4cf024ae16eef530be28b2d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "9aed80199b8ebe6945c880707cff3651a4f3a1abdf9d8c79d8172182c0d82196"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.aarch64-linux-gnu-libgfortran5.tar.gz"
[[HSL]]
arch = "aarch64"
git-tree-sha1 = "50cf135ac239c7e6e9994511f329c7364d1df453"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "10cf9d43cd3ee4dfde871109bb340f9d4d8b35102d3db94feee0f625d2176985"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.aarch64-linux-musl-libgfortran3.tar.gz"
[[HSL]]
arch = "aarch64"
git-tree-sha1 = "a5a7ee48458b86efd05bb7a994fc4a7780ecb4b0"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "2136c623e45f4331da4cd349b514ade2fcfdd28042ab26e38037f783edc41681"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.aarch64-linux-musl-libgfortran4.tar.gz"
[[HSL]]
arch = "aarch64"
git-tree-sha1 = "4a45a16c6ebfbd1cd5e98343c6326c5818250fb6"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "f131c9f491c76560384d5c6b77449c8b4e2231152de91fc7bca78fe095110a67"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.aarch64-linux-musl-libgfortran5.tar.gz"
[[HSL]]
arch = "aarch64"
git-tree-sha1 = "10f80bb411ea076d12770a0a8f154e8295bd24dd"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[HSL.download]]
    sha256 = "87315b6141bca9c05d4b98520d648a547cd68443997a7df8d655e938f53b23f2"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.aarch64-unknown-freebsd-libgfortran4.tar.gz"
[[HSL]]
arch = "aarch64"
git-tree-sha1 = "39d792a24e4033aad1ad90b42b79bdbbc5301cbe"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[HSL.download]]
    sha256 = "be61265d92a6a01d8e9679a25c23e13f045b033506e3e44c740d0db76f6324f5"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.aarch64-unknown-freebsd-libgfortran5.tar.gz"
[[HSL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0e8f5924de03f200e835575027d12d17d0084b2a"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "1b5cd732e722659f2d76f94c182999a46399a7d40de84321fe602bd7fb32a2ab"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[HSL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "930625d0750897b97f82e16943a859e9ac7a50e2"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "c7a163c71313f72d43b10a711ad3f76eec8e584c288679c48433cf8d2df5ab94"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[HSL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "29107aedc829cbaf637022739686ed70af41185d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "57ce50d5e9749599ea6db3f876d394491f73d27194e60f9b8b1a48e5905ad152"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[HSL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f901b969133baeab220c4e9a45f788e2263d2517"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "23cd4ecb33e3f48ac69cb0a258bce9033f715773dfc962ebbe0bd0b7e3a79e8b"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[HSL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "657c7a5f84f240d0dfcd33d323a65b85b8c6620c"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "318fe9100f8a4027edf5b9240e3739c69f37dd5ada44acada49b2fd848548b44"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[HSL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5b362a12d996deeb74da0b7d81ed681686da4d57"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "76d2edbeed98438aa067ac980f3b08a6a1a94aec6103bd18e30e9f19cb4f8cef"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[HSL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "56dffbed7d023a116bcd8ab7f08f263dafd90264"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "c03f6ea063ee8b1dcd2c91ff61a1ca6a40118c7fda70db2fdb7fdcab498000ec"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[HSL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4dbe0e99ff0fe7b69ad617f4c0fd25f3ff9632c6"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "7482d4ac272e130b78c0205cc1aeb404252235b4fe03362056600f932de46dbb"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[HSL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b4bee8edd53538befa114664dc5aa257f9ea26b3"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "cb2f2cc8407c38b3e6dcc46033e4f6c62e01af13529b3d79ae07c33b8fe7a644"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[HSL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c94b5cc5157637fa8b0092780aafb86597f6eac9"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "d53bf4965b1bf9901547517be061ecd8cadbfab8c0af3be80f962ee8df255118"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[HSL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5689478ee5de25961b2cfed61f515f270e00bc44"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "6f6c32d61ad6c0f05a7f352e88d85dd036f92db2d7e7e304de42a3a0c1bb2ce2"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[HSL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a585cf44bc4ece9ef4729b5f41555cd8f11d4c52"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "fd1a4b8ad2067d266611e3ea7e973566264ee129b30dc6fee8344816d3e8a3e4"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[HSL]]
arch = "i686"
git-tree-sha1 = "321e8fb5238293a24b1602c8bfb057031b91b694"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "9a5aecec68b0341480b768ed547f9d6cfff684649ddf0a1e4ccde0e970d4e6b6"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.i686-linux-gnu-libgfortran3.tar.gz"
[[HSL]]
arch = "i686"
git-tree-sha1 = "dec4d062d7cca92896acc50627bd4a61dd1e3d44"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "7c27f87c2a1a97942bc4a1664cdf100e2652af04aefc4421e44bfd49facd47d8"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.i686-linux-gnu-libgfortran4.tar.gz"
[[HSL]]
arch = "i686"
git-tree-sha1 = "9deeb4ebcb05824e150c0f5b5244a8a22ce883e9"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "ff2857c40ead783dec22d2b4f6560a02c23072620bdf940c84275286d8c204ad"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.i686-linux-gnu-libgfortran5.tar.gz"
[[HSL]]
arch = "i686"
git-tree-sha1 = "b345da69553985d3395c447ee6aadefc3685a27b"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "cfa80f0b72e77c3b6ab63eac6998e250a0837ee3f643c4b280ad868ff9083fec"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.i686-linux-musl-libgfortran3.tar.gz"
[[HSL]]
arch = "i686"
git-tree-sha1 = "c2f73540f64bb1cad29d8955d6f442d5d8f16968"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "69ab3877ada7915a3d9c8e7f8d7a2ea917882e2fd42a21f57703a8b33cfd72d6"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.i686-linux-musl-libgfortran4.tar.gz"
[[HSL]]
arch = "i686"
git-tree-sha1 = "d8d27f95151ed68c99d5d7a4dbb80a4f80c9b333"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "bb8ce210bbd26336ef63d7f8d6d509a3c23339ff0d4c9b47e15492b2ff8554f3"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.i686-linux-musl-libgfortran5.tar.gz"
[[HSL]]
arch = "i686"
git-tree-sha1 = "70bb6aad8524315a6f3e45b8ae2b7b288f7aecdd"
libgfortran_version = "3.0.0"
os = "windows"

    [[HSL.download]]
    sha256 = "367ed9c6735bcd550b9e78426af3495d8663d40935283a1842392270efccb48a"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.i686-w64-mingw32-libgfortran3.tar.gz"
[[HSL]]
arch = "i686"
git-tree-sha1 = "985de046d8766bd3c3eb2c0b2b4a6dbd61fb5b8d"
libgfortran_version = "4.0.0"
os = "windows"

    [[HSL.download]]
    sha256 = "ee58a6318c0fc4729ba28eb8bd496c029406abff25466ad1443185d7175b9787"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.i686-w64-mingw32-libgfortran4.tar.gz"
[[HSL]]
arch = "i686"
git-tree-sha1 = "eb4b0ea54de57586b74d80a038332e485945c15f"
libgfortran_version = "5.0.0"
os = "windows"

    [[HSL.download]]
    sha256 = "6ee1ee20b0ad111c3beeb80436c0e16dbb96141975d26292f77891a8d1583d76"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.i686-w64-mingw32-libgfortran5.tar.gz"
[[HSL]]
arch = "powerpc64le"
git-tree-sha1 = "3d36f9735e3af471e2abadf9f1e0d665af771a4c"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "d73232be1fbe4359e6f8b0a23533df3d245c8b281eed1fb0415805316dcefc55"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[HSL]]
arch = "powerpc64le"
git-tree-sha1 = "413be4a858404156aad638bb9874055fa03a94b1"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "59620425ecfc9ad4cb629bff1481fe113ee07b6a3370818133286443884c72ab"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[HSL]]
arch = "powerpc64le"
git-tree-sha1 = "65475631d1a006be02a45b9965eeae726504f323"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "ae98f2011ffcf856daa48c6b8a29b5754dde9e1ac0b18d6859266f78a2202be5"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[HSL]]
arch = "riscv64"
git-tree-sha1 = "137c237fa0ac8ce057d498a0ae0626d0846e6027"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "e2bc9552ea95b33eb6f873efff477a6b69cf18f3c24ea18baaaf9e9a61dda52c"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.riscv64-linux-gnu-libgfortran5.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "e2610d6cba440ad529af25565c15b6c6ba7426dc"
libgfortran_version = "3.0.0"
os = "macos"

    [[HSL.download]]
    sha256 = "59cfa9af36fccf7624a6b8d4c3de53f1343d1faea12b2454a7e742620362f0fd"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.x86_64-apple-darwin-libgfortran3.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "98955df5d96b2ac211a7f9e82ae9d8ac5c2a6dc8"
libgfortran_version = "4.0.0"
os = "macos"

    [[HSL.download]]
    sha256 = "c9cf1606f632e72d9cad6fdac8641e66f9716af74e904c6f5bed409a40d9a752"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.x86_64-apple-darwin-libgfortran4.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "933ec4740052840b36e6910621d736909248487c"
libgfortran_version = "5.0.0"
os = "macos"

    [[HSL.download]]
    sha256 = "6ee8ffd2dc408f9f4736f40b45e867af15489a530d8974b04a5025b7a37aa67a"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.x86_64-apple-darwin-libgfortran5.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "158961e2191d3589a5d91847153d9f86b10f819e"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "17cd84d2b0af98f9afec8b0da0ba2c0927edd29a0282d355964300ac53b873e3"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.x86_64-linux-gnu-libgfortran3.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "a7b3d2aa0d86a9940dbee7d11bdb5b2ad89aa9b2"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "53c8495a90e1d5b6afae33a826c1ac9645cbc84f5b9cd7cfedc858c9d9973014"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.x86_64-linux-gnu-libgfortran4.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "53e38c0ace7d93f4a8cd6435c6fd2b7070659772"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "399e42dd0af07977995f0b1444ad107f4b796345935b84906fca9c1f5364258d"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.x86_64-linux-gnu-libgfortran5.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "1cd2d9203d63a8b9d0ed19aae759e071a6ffae91"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "f08875e06c5070a0f6b523221faf819b503bd4bd719a361ea6dab2207e61ff46"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.x86_64-linux-musl-libgfortran3.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "2020f23b3d044ce0dbba896ca772053c2db772ce"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "2f229321cb3959e434dc9624a868f771cb86c8d4e52585467d69df9917d2bd28"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.x86_64-linux-musl-libgfortran4.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "a780dd8f521230d543ee641d098c0dc8d7556507"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "9e7553df6697e6e52081c77abd72846a0456d33864a0bed775e38c79df92e1bc"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.x86_64-linux-musl-libgfortran5.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "6a12f371c23437d16afdaf26e76198d2360a75dc"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[HSL.download]]
    sha256 = "cb3b533e9503bf89f49fbc3d1eb3bf7b13584fb8ec7d03b731166e71c8f980ec"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "64b1d7aed94a40d31ea82046d94ca3cac0feb926"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[HSL.download]]
    sha256 = "11e7e515445fc5164fa457270bd9108d034b7cbe0be012bca3cf86d1dcede89d"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "fde4d4fd1fab39e56a5c33a0e6a847627b35a2be"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[HSL.download]]
    sha256 = "a02919f0b483bb3ace1da579ef9b502b02696c98f81dfba49b7c8eaa46f77085"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "be7e72adae227dbdd8b505018f1931b4540e982c"
libgfortran_version = "3.0.0"
os = "windows"

    [[HSL.download]]
    sha256 = "8fe99bd55d6460e91c4fe2d9e0ff309c883132c1f7c62e3c7a651c5c6c8bc2fb"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "9d48cf14289dee1d04556bb922ca8f343581472d"
libgfortran_version = "4.0.0"
os = "windows"

    [[HSL.download]]
    sha256 = "0c11901e30f0fb47b7e2b2f8fef5e213dc1ad67dabc3c750f297b7e03b900a01"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "f0d8c6ae06f6430e3820b665fea87c68e5e0b71b"
libgfortran_version = "5.0.0"
os = "windows"

    [[HSL.download]]
    sha256 = "4b4def40b17fd09151d27d9d92f3dc4165d18f3b2a583d027dbade2f5367e24d"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.2+0/HSL.v4.0.2.x86_64-w64-mingw32-libgfortran5.tar.gz"
