[[HSL]]
arch = "aarch64"
git-tree-sha1 = "a2655672bda517e1de01150f669d2a43e1cc7b12"
libgfortran_version = "5.0.0"
os = "macos"

    [[HSL.download]]
    sha256 = "168e36475bab0a095ddca194e011396b2c18ee00788c772fd460b42145264554"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.8+0/HSL.v4.0.8.aarch64-apple-darwin-libgfortran5.tar.gz"
[[HSL]]
arch = "aarch64"
git-tree-sha1 = "4c54f0beb182a78fb85cc0dbbfe5979cabdba493"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "c696cc77b863f3ca31bb9bc4b403c21c1aa7356121df0be3c23c4dae62f4de35"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.8+0/HSL.v4.0.8.aarch64-linux-gnu-libgfortran5.tar.gz"
[[HSL]]
arch = "aarch64"
git-tree-sha1 = "906aaecb82b5ed5e6626da7df414b04c0ef6dd30"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "62d57d8e28b10617cbe7e2b82cc2e8358820adc3717aeca42f16504f91944679"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.8+0/HSL.v4.0.8.aarch64-linux-musl-libgfortran5.tar.gz"
[[HSL]]
arch = "aarch64"
git-tree-sha1 = "6ba3268c1284be314a69fc1b96e16d2766d9a7cf"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[HSL.download]]
    sha256 = "444daec983f91dd4d82c98e861e992d993bea638fca00969d642fdbc7f7613b6"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.8+0/HSL.v4.0.8.aarch64-unknown-freebsd-libgfortran5.tar.gz"
[[HSL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a401d1ede46c63ccbf9a1e6e237c114fb5fc8e9d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "3fdd73689fe838285782b7d827033bdbab3bf1e1b9ad98a38c65b0a457558a99"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.8+0/HSL.v4.0.8.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[HSL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "566d8f8394fc6a0f7703009103f1b26de8a24132"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "521b6e5fc24e0e19a34c8377ef07dd5b377f1ee24132995e016acb0af5bedc4a"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.8+0/HSL.v4.0.8.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[HSL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8b4029ddb29b97c0b2787eedffa2b75d6aac2639"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "ac804cfbe5b5449167583d1a405dbc3efbbb963c2041774956bc10d9777191f3"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.8+0/HSL.v4.0.8.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[HSL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a69235b7d372a9b5c887e06e4985ffe476528f57"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "d79a8a5b765db42c2b23c2bef3727a33714aa29bc80d41191b908b3a2171dcc6"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.8+0/HSL.v4.0.8.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[HSL]]
arch = "i686"
git-tree-sha1 = "75e0c9ea149e9487bff3b30ac3b766fbe92ad0c1"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "acff1964c54166938e306d39507734ba917b4d2ed0656b2fd03fede18752e783"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.8+0/HSL.v4.0.8.i686-linux-gnu-libgfortran5.tar.gz"
[[HSL]]
arch = "i686"
git-tree-sha1 = "599db0017d70f00dc1f4cffca41619ccefa7b0a3"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "adcf70a6dff36d29a3a4e6afff2a50a2ace3f0056ae5938066af5b42f5211558"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.8+0/HSL.v4.0.8.i686-linux-musl-libgfortran5.tar.gz"
[[HSL]]
arch = "i686"
git-tree-sha1 = "611692eda7dae2e945f4817775d5a8a7c68ce145"
libgfortran_version = "5.0.0"
os = "windows"

    [[HSL.download]]
    sha256 = "2c306f3c132a1a4126c0ec22354eec6a05cb287c18fd3810a7d4d1638ab2f203"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.8+0/HSL.v4.0.8.i686-w64-mingw32-libgfortran5.tar.gz"
[[HSL]]
arch = "powerpc64le"
git-tree-sha1 = "40d80dbc1f28e550b27ee9d030b9e5ab01cd91bd"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "d349e351357ce6adad6532ebc11a8e3be73d3d2a953772667704ae727e355522"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.8+0/HSL.v4.0.8.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[HSL]]
arch = "riscv64"
git-tree-sha1 = "e4ef42b5ed41a6e190534402024bdbba6b8578f5"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "6f4e480ef6691294236ed28153022747922119fbb08850ed655666f3d9d863d7"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.8+0/HSL.v4.0.8.riscv64-linux-gnu-libgfortran5.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "6ef69b256a6dd9267ead71a1b5f3fd110dd4b879"
libgfortran_version = "5.0.0"
os = "macos"

    [[HSL.download]]
    sha256 = "76beb3f6578368b3fa764ec58d89339f7eca5d4b5ade8b1c0934c07ff4263f2d"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.8+0/HSL.v4.0.8.x86_64-apple-darwin-libgfortran5.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "2f96a8b2eeb297bd97c78d39790f5e5d78d7b84c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "2de98d8e4bf292cb47ee9f45e8e978fde232f724c888528e9f50483441b2ceea"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.8+0/HSL.v4.0.8.x86_64-linux-gnu-libgfortran5.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "a9726379e2c00d7403964f6767a79366212b8a9e"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "f0ee20f45e2b2afdb17f6c3b1b823f1e2b9c89bed8a2c19d4509fc9620754705"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.8+0/HSL.v4.0.8.x86_64-linux-musl-libgfortran5.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "f1513086005884ea90d799f3d111c0b8d145e99a"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[HSL.download]]
    sha256 = "f364206da7483437169ff95c0606bf04cf78da160effd7c63a60869c3c54f46a"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.8+0/HSL.v4.0.8.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "ace2fdcbc6750552c343691d6ae61d3c1a6ffcfd"
libgfortran_version = "5.0.0"
os = "windows"

    [[HSL.download]]
    sha256 = "345b7c253f9590762667f566179eb4f4188051404c5f64f060866e0962c50aab"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.8+0/HSL.v4.0.8.x86_64-w64-mingw32-libgfortran5.tar.gz"
