[[HSL]]
arch = "aarch64"
git-tree-sha1 = "e04758bee3b54e6beff189ac80bf85336c66391a"
os = "macos"

    [[HSL.download]]
    sha256 = "344c08260cfdd78ac1c0cb65067694cf639f4debf967bcbca0b1562c769374ed"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v2.0.0+0/HSL.v2.0.0.aarch64-apple-darwin.tar.gz"
[[HSL]]
arch = "aarch64"
git-tree-sha1 = "9e3c0042dafa014a4b211d78966c934f2aaf9711"
libc = "glibc"
os = "linux"

    [[HSL.download]]
    sha256 = "fc9ad68b4d4760206cd31ed8b0623b4b336bc671eb731995d25104ac8eb3bfe4"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v2.0.0+0/HSL.v2.0.0.aarch64-linux-gnu.tar.gz"
[[HSL]]
arch = "aarch64"
git-tree-sha1 = "effb3960e31092d1b302cffd6caffd11a3c38c4b"
libc = "musl"
os = "linux"

    [[HSL.download]]
    sha256 = "781ed91adcde0d5c6e230d673f837931b5ba6d9fe4c938e99eeeab39447a7db3"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v2.0.0+0/HSL.v2.0.0.aarch64-linux-musl.tar.gz"
[[HSL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "53f1ce8bbfc6ab7bf8c99c682aa69b06150e34b1"
libc = "glibc"
os = "linux"

    [[HSL.download]]
    sha256 = "a66d3fe584f3281eb27cd5eaa3b1937698b2106d31c07ba137f48df131354ff6"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v2.0.0+0/HSL.v2.0.0.armv6l-linux-gnueabihf.tar.gz"
[[HSL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "11079644a4abbaa5cbf9f0a1c6e14fc18c2bd8ea"
libc = "musl"
os = "linux"

    [[HSL.download]]
    sha256 = "d32ef3caa288b7394ba0b335e7bae7a40779a25664266b712060636aeb17c5e2"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v2.0.0+0/HSL.v2.0.0.armv6l-linux-musleabihf.tar.gz"
[[HSL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ae0809a003e5b47bd7b42a5a5241700977dffe5a"
libc = "glibc"
os = "linux"

    [[HSL.download]]
    sha256 = "1c9cb1f42f7f2dc9b7d4189b54a2bf9f5f4a04ce5a9a92b57ebfa244346beb43"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v2.0.0+0/HSL.v2.0.0.armv7l-linux-gnueabihf.tar.gz"
[[HSL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "62a4d787afa82612ede8c52462948b638392a8a1"
libc = "musl"
os = "linux"

    [[HSL.download]]
    sha256 = "2fabad17dd9a5a56fd2643382ce5dc366977da8040b432a70550687c4a82cd5a"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v2.0.0+0/HSL.v2.0.0.armv7l-linux-musleabihf.tar.gz"
[[HSL]]
arch = "i686"
git-tree-sha1 = "e6ecbaa138cb0bf5b9f115edc37dad87be61f8b4"
libc = "glibc"
os = "linux"

    [[HSL.download]]
    sha256 = "58737cdfe3e3b4de420021e6ac0f1d3ce0a1c3957cd915a8ef473fba0d5efc2c"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v2.0.0+0/HSL.v2.0.0.i686-linux-gnu.tar.gz"
[[HSL]]
arch = "i686"
git-tree-sha1 = "b1cdcbef2ee3e086b9ef3d4d82eed30e45162a4d"
libc = "musl"
os = "linux"

    [[HSL.download]]
    sha256 = "f625a90badfc4a2d38a39724ac0c1f300d8ec271bf1a10e3eaae7bf290939150"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v2.0.0+0/HSL.v2.0.0.i686-linux-musl.tar.gz"
[[HSL]]
arch = "i686"
git-tree-sha1 = "eb280e094802383bec6341a8eede64124520e0b1"
os = "windows"

    [[HSL.download]]
    sha256 = "7eef9f266b4d1eb626ef1aa54a47a5420b9985c742e23ac5cf45c183927c04e5"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v2.0.0+0/HSL.v2.0.0.i686-w64-mingw32.tar.gz"
[[HSL]]
arch = "powerpc64le"
git-tree-sha1 = "51ecec4ed7ed6b5b30793e8b7cc9d15cb2a10cc8"
libc = "glibc"
os = "linux"

    [[HSL.download]]
    sha256 = "f39e890b7352e8aad71f8c738e4e0282b7041cb6a768cab21f84b620384969f7"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v2.0.0+0/HSL.v2.0.0.powerpc64le-linux-gnu.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "5b1ee9a1f43405d217e65aa634d37d1ecca3576b"
os = "macos"

    [[HSL.download]]
    sha256 = "9ec61ef0f4b4d87f4088090dec17fc98285384fa62937cc2d1b7572efb975271"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v2.0.0+0/HSL.v2.0.0.x86_64-apple-darwin.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "d66a9ad3ab08b6453bbe78e728fccc106f5a1050"
libc = "glibc"
os = "linux"

    [[HSL.download]]
    sha256 = "5bbae145c56b4651a2ca78417c2a5494cc8a55fc3373cceaadc1efb2222df66e"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v2.0.0+0/HSL.v2.0.0.x86_64-linux-gnu.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "32ceaa137dfcc9c2a990d65eecedb683bbf6c5f6"
libc = "musl"
os = "linux"

    [[HSL.download]]
    sha256 = "2020c548858d6f5baaacb1bf1f923afc15f22ebe7998e8a63bce699624a783cf"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v2.0.0+0/HSL.v2.0.0.x86_64-linux-musl.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "9d01076f43a04cb381333821950b3a1ad8726def"
os = "freebsd"

    [[HSL.download]]
    sha256 = "20c29b30778a9fb78f24c6fb733bbaa4fdb70b50fe5117826668158bf0c89f57"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v2.0.0+0/HSL.v2.0.0.x86_64-unknown-freebsd.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "6a9bbd38c80718e9eb6d302c238dd2e422140665"
os = "windows"

    [[HSL.download]]
    sha256 = "922668583f85eebf72f2f8d3427e97028f1777ef171edb97372dcda244b3a6d7"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v2.0.0+0/HSL.v2.0.0.x86_64-w64-mingw32.tar.gz"
