[[HSL]]
arch = "aarch64"
git-tree-sha1 = "dd41cfbea4ae0c6594169c578d098354438a4e64"
libgfortran_version = "5.0.0"
os = "macos"

    [[HSL.download]]
    sha256 = "0b45f88a96bd10b6ac70a876c472790af2d34702e1310d6226ec44ea88b10a03"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.6+0/HSL.v4.0.6.aarch64-apple-darwin-libgfortran5.tar.gz"
[[HSL]]
arch = "aarch64"
git-tree-sha1 = "cf169e1a72ab2c67386ecb64e931f000275250bc"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "bde25ad7dd68ae28d5bc2ed1b1fa859c17c7f845f1ef67e32d9c996be5fe5811"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.6+0/HSL.v4.0.6.aarch64-linux-gnu-libgfortran5.tar.gz"
[[HSL]]
arch = "aarch64"
git-tree-sha1 = "800bf7ce53934ced0495930ddc57c5a44932e8d5"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "9a64305f2d142786659993044e9b368da8d5f2fbc138307fef33667ad0f6ff37"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.6+0/HSL.v4.0.6.aarch64-linux-musl-libgfortran5.tar.gz"
[[HSL]]
arch = "aarch64"
git-tree-sha1 = "db6bcc68dcf908a962e23f16ea517081bfa83be0"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[HSL.download]]
    sha256 = "7b14b8270ad11fd13ba08f6dfa173afe019556911d69286eb56a2c32980a0534"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.6+0/HSL.v4.0.6.aarch64-unknown-freebsd-libgfortran5.tar.gz"
[[HSL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0545cf12297a12f24959d40b38b54cc47becdb51"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "7fdda7ef1cb8bb7cd1c0cb8190135990caa23104d208ee742058843bcdd50c3a"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.6+0/HSL.v4.0.6.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[HSL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "65c7d331a81fa5909de84e9ba802ffbe1bc2e8dc"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "8ae789639c6e8c4ef16676b63f10e4fcb5e2c0c698d5850d832e8b70e77335a0"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.6+0/HSL.v4.0.6.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[HSL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9c7bfe9c59433e000612caca9c723a31f3fc0628"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "52221605ddfab21a230a7245f2ca01686c4bcc424ac7f04f71ce9a94eacabae9"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.6+0/HSL.v4.0.6.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[HSL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9933bb1631ba38ea22cbf4d07d4521da3068fbf6"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "c8b952dd9b90d13f8a42378f8833d22823478f7bc283f1ea9c98fa720ed6ef22"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.6+0/HSL.v4.0.6.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[HSL]]
arch = "i686"
git-tree-sha1 = "dfc55bc50dcf6d531b0e01813030efa9a7c82774"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "4cc08e8dbaeccb0c816df119d151ac1e0852b70252db1e0c4b148545da7ebd95"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.6+0/HSL.v4.0.6.i686-linux-gnu-libgfortran5.tar.gz"
[[HSL]]
arch = "i686"
git-tree-sha1 = "65385924746f5a14d920fe40ef8bbb8e073d3558"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "471f41543dd5cb0aa564fd43b05b3a0cf6da83210615a833c4143ef2832711d2"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.6+0/HSL.v4.0.6.i686-linux-musl-libgfortran5.tar.gz"
[[HSL]]
arch = "i686"
git-tree-sha1 = "98bb2cbb60d150935db68b97eef5c0636a29ef1c"
libgfortran_version = "5.0.0"
os = "windows"

    [[HSL.download]]
    sha256 = "bd7d889f3b03faf267891e76436ff88ae5e34728b4249f35e5a6dfaa6b930477"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.6+0/HSL.v4.0.6.i686-w64-mingw32-libgfortran5.tar.gz"
[[HSL]]
arch = "powerpc64le"
git-tree-sha1 = "58c29a6b8f0f10fc953f66d32d6daf52e451c36a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "562fe2b43d7f239b24611c8bf8880f0d4afb3314c618e4d79c75a37ff0e74e65"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.6+0/HSL.v4.0.6.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[HSL]]
arch = "riscv64"
git-tree-sha1 = "ef50079ab78a387067e408fb7c7c19352cc8670e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "d7a4bdfc500ab7ece0a7385415892ec0850379c84d060e5929c1466571a55a92"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.6+0/HSL.v4.0.6.riscv64-linux-gnu-libgfortran5.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "337e3575283cd4845edbf65c1a8aafff2fb92945"
libgfortran_version = "5.0.0"
os = "macos"

    [[HSL.download]]
    sha256 = "2f103d0412a8755e8db15568b7b6771d1b044b514eb155c1c10cf8d9fc3efcb8"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.6+0/HSL.v4.0.6.x86_64-apple-darwin-libgfortran5.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "1a92e5b95830b425db1ad8f555e08f6479e0cc7f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "bed9d44055c490e1ad81446842721d827394429fe54ebbfb7cd4bd25cadc289f"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.6+0/HSL.v4.0.6.x86_64-linux-gnu-libgfortran5.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "9461b062bd0d8b7675261d7fe6a9a9b74c83dff8"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "ed717cf49e84da36d15fe309c8de6a40c921c12b783e342c5a4e1f380d31aae0"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.6+0/HSL.v4.0.6.x86_64-linux-musl-libgfortran5.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "6c7baba16cd964b9dc89f5721311ce405e2710a5"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[HSL.download]]
    sha256 = "86e9428f8c0acac8b8e7f040a22e2313e09844118e88e203ba0f6d04c038263d"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.6+0/HSL.v4.0.6.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "e6a0c9541e2ca264d7368d02ee1ca4ca8f471a58"
libgfortran_version = "5.0.0"
os = "windows"

    [[HSL.download]]
    sha256 = "0328d61dd008cd28997d9e1d6d04764454e696ff9fbdd74a072f78e97a682cb2"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.6+0/HSL.v4.0.6.x86_64-w64-mingw32-libgfortran5.tar.gz"
