[[HSL]]
arch = "aarch64"
git-tree-sha1 = "d810eb3949e0a77092f0b3e0d9c5fd36924d5aa9"
libgfortran_version = "5.0.0"
os = "macos"

    [[HSL.download]]
    sha256 = "14e115bbff2dae8c8525179941f259f796e4c61bb18d1b45408c788e98b27c8a"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.1+0/HSL.v4.0.1.aarch64-apple-darwin-libgfortran5.tar.gz"
[[HSL]]
arch = "aarch64"
git-tree-sha1 = "59894cbddd2f8c7a5040a0769cbf285537a0c730"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "87bfbcd4611f6de82f578fb8c9201a9127f75a7066d25317d1bae7aa90b89a84"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.1+0/HSL.v4.0.1.aarch64-linux-gnu-libgfortran3.tar.gz"
[[HSL]]
arch = "aarch64"
git-tree-sha1 = "51a4766890c257d030140e74e83f1ad26b7155af"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "8f6b1d1663f74cda281ceb1283e3d5cc6d28efb68dd8c3179db1dd5393ac91ad"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.1+0/HSL.v4.0.1.aarch64-linux-gnu-libgfortran4.tar.gz"
[[HSL]]
arch = "aarch64"
git-tree-sha1 = "56bb525faebf6d23b65f462276d8505c9d54edf7"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "349e750b141e2b6dd4a87721f015e792ad1e5a8b1c6658d9d9615f9a83aacdd0"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.1+0/HSL.v4.0.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[HSL]]
arch = "aarch64"
git-tree-sha1 = "ac134773e5f539eaa81580b6048de8d631e781d8"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "2f05525c2921efa94de3df793c4ed78073a64c9cca3b31a84956f727a411296c"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.1+0/HSL.v4.0.1.aarch64-linux-musl-libgfortran3.tar.gz"
[[HSL]]
arch = "aarch64"
git-tree-sha1 = "db28fc6a60d8382aa21550ffa7dcb7b1d7db2b28"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "016d1df4d303b71735d7665edc1e5d71ad28e8ff5e607d28e333fc1be1e51780"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.1+0/HSL.v4.0.1.aarch64-linux-musl-libgfortran4.tar.gz"
[[HSL]]
arch = "aarch64"
git-tree-sha1 = "fb77cf3c2340c42059a83d65451e96a2a17f384d"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "3786ab2038b4875015ded7ed4f89179cb782ce617d2b30b39c060be9fc40d02d"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.1+0/HSL.v4.0.1.aarch64-linux-musl-libgfortran5.tar.gz"
[[HSL]]
arch = "aarch64"
git-tree-sha1 = "77a15b7c97372bbbdcaa3ca6f7d5eabb19b71379"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[HSL.download]]
    sha256 = "08ac945de72ec9ebdeec2e07befab36d70b1ce47f6cbec75b3eb8184bc0772a4"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.1+0/HSL.v4.0.1.aarch64-unknown-freebsd-libgfortran4.tar.gz"
[[HSL]]
arch = "aarch64"
git-tree-sha1 = "d90854d30a92ffe1f96fc95bdb5733e08ae66206"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[HSL.download]]
    sha256 = "3560e740ab63ecd8c16d75f16d3bb8df24a5eeb66a10c97ac81d580e6fa8c220"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.1+0/HSL.v4.0.1.aarch64-unknown-freebsd-libgfortran5.tar.gz"
[[HSL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "beff1df115b8c03546ec97fe0eae36f0dd3c2073"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "a44dc29ee93e3cb2f0874e8fe30ee49117daccf0e009899343093089a74fd192"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.1+0/HSL.v4.0.1.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[HSL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9e1604b41ad679749038fbee97050fe9a29f2c3c"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "883c10104fc9acdf69188987a37a5ea7a6ddacf4320f1af4916c1a2b420e12cd"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.1+0/HSL.v4.0.1.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[HSL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3d65c52ef80c6dfca13d3e186078a38869db6b15"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "770b719473ba146831656fedcac315b904db7e461453e3b5c3bb6ea7f3341774"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.1+0/HSL.v4.0.1.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[HSL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9db9aab1151888917a12abf86110805c7c1bdf2c"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "4e6364aa76175a0d7647368b4577a7111bc7c6c587e4009662c8a6de5211d230"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.1+0/HSL.v4.0.1.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[HSL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "68a919a548b4fe67051538984d22096eb2072971"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "bf600aa4eeedb4399818002db1c2dea613b56728c45f6b388bc4d8746045e6c1"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.1+0/HSL.v4.0.1.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[HSL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2f8b71dc65f7ca3bd7654dcfe10aac8b4245962f"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "eedd69d33e7ea5f29d0ef6e1443142fb6721e007f0554f43fd858ebeb8dac980"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.1+0/HSL.v4.0.1.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[HSL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "25a2a76eec8b94a48bc99709e7fae412f1feac84"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "657c8add1f19920215ef2ecd31381842aa8eb0f41e89efe2c0549580a4e4f82e"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.1+0/HSL.v4.0.1.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[HSL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d993a09f46b377eb668bc40c9d47665213d9a668"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "cd334a39f84055c6d5118fb435d864801e36e07da00934a02c014909d49fa873"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.1+0/HSL.v4.0.1.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[HSL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "34d8a54a0b93a08ca3e246552334b82f500147e7"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "667a6283916647b1bcc6cc98389add32f1fcfb24379606a41cb08af94c6574e3"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.1+0/HSL.v4.0.1.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[HSL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ead2b6b9b428ce871eddd21400aed2ef5979480a"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "083f0799c27c2cba8b2736cf6dc1fc6d12d820e43713b43fb92f7625326c997f"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.1+0/HSL.v4.0.1.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[HSL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7d2845c2468ae04ffb6f1d904c6f4518ed8fb8ea"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "57205e254ba13fc020e73f5e5c57ddb0d3e7007a5af6a4dd06756ac1952c2cb2"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.1+0/HSL.v4.0.1.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[HSL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5e51bc13eb8ca20aac79da21dfc55c4077a7cfbe"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "7f4d8bbc3b57f58b8805a93b99bbf671662fcc22e11e76fea3f983bbec202e2e"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.1+0/HSL.v4.0.1.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[HSL]]
arch = "i686"
git-tree-sha1 = "34f11a1b7b982059c76a9c1bab7c9ba4a9a25219"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "9bf75a8702e3c68459ea655dcc526f7d9fd8aa189715ebb137ec1b132e736aaa"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.1+0/HSL.v4.0.1.i686-linux-gnu-libgfortran3.tar.gz"
[[HSL]]
arch = "i686"
git-tree-sha1 = "cdffb7817252592efdd27c35e3380388fede73a4"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "b42c110107d07def3ae4ff407d5e0d075dfe020bcb656c1326be97587588f538"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.1+0/HSL.v4.0.1.i686-linux-gnu-libgfortran4.tar.gz"
[[HSL]]
arch = "i686"
git-tree-sha1 = "e76c95b317edcf07db56c20de09c13182cd2fdfc"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "87a72b046fdc77e4e6b2b05b9da32e2436fc835f2eb690f00633917208b7e35f"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.1+0/HSL.v4.0.1.i686-linux-gnu-libgfortran5.tar.gz"
[[HSL]]
arch = "i686"
git-tree-sha1 = "daa1e1a097fdbac02496f2af08560cc9bb778918"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "a47c010d52a521ee4042c821ede92dac56dca22da4d27aa9f0a00276ce0df439"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.1+0/HSL.v4.0.1.i686-linux-musl-libgfortran3.tar.gz"
[[HSL]]
arch = "i686"
git-tree-sha1 = "c7136da69c76d49684f30549e30686b9291180c9"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "d73ad6743b18f022cd1e3ed0406db8793bac39a2f8c4a727d1743520526e1f24"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.1+0/HSL.v4.0.1.i686-linux-musl-libgfortran4.tar.gz"
[[HSL]]
arch = "i686"
git-tree-sha1 = "f4ea03fff349d7701b4a8898da3ec6925438277a"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "845f158f6c9e3c36674ee77fb2b7f6974b8c8f14aac1e6923172940dc8134a4c"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.1+0/HSL.v4.0.1.i686-linux-musl-libgfortran5.tar.gz"
[[HSL]]
arch = "i686"
git-tree-sha1 = "5fb874a17d8adeb29e8eeb55c1c06cd72a95e91b"
libgfortran_version = "3.0.0"
os = "windows"

    [[HSL.download]]
    sha256 = "cd0ce195cdffc3d92c427b52d006c3e3280294350083acd76c9e18bd894c9922"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.1+0/HSL.v4.0.1.i686-w64-mingw32-libgfortran3.tar.gz"
[[HSL]]
arch = "i686"
git-tree-sha1 = "fd483e0dbaef6137f6cf84aa22f789ba33b3a8f7"
libgfortran_version = "4.0.0"
os = "windows"

    [[HSL.download]]
    sha256 = "968621ea1f752b35a423be1d7916f713e23438702fc6a772f251f30a39fe2547"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.1+0/HSL.v4.0.1.i686-w64-mingw32-libgfortran4.tar.gz"
[[HSL]]
arch = "i686"
git-tree-sha1 = "2a6dc2db45cf97f208f53ffacae4347484d84028"
libgfortran_version = "5.0.0"
os = "windows"

    [[HSL.download]]
    sha256 = "57a701ca5171ecc0ad9ab3274e8b61575838e9c41b9b9562004d9b68ac01b673"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.1+0/HSL.v4.0.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[HSL]]
arch = "powerpc64le"
git-tree-sha1 = "375484b94541618293869abec7b8fa73619c4dc5"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "3bea81e5b194d97d26062da3f6fa36a5786696e2044b458097dae3ad3a08b959"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.1+0/HSL.v4.0.1.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[HSL]]
arch = "powerpc64le"
git-tree-sha1 = "345b1661a0293ab16c89cd45052ade7acc69c3f2"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "9f250be9b9a128a01739bf268be904a3c171b58d9d27e0125db04ea64af89f9e"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.1+0/HSL.v4.0.1.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[HSL]]
arch = "powerpc64le"
git-tree-sha1 = "d470e0f3f64b42e7e506d376c6e85c9b80cdf95c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "709c62328abdba076fef294608139079d1cef0bf8fc2f5a74cc05045d80a9ba2"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.1+0/HSL.v4.0.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "b76e459b5339e971e1e6b2cc92c955bc6254a00e"
libgfortran_version = "3.0.0"
os = "macos"

    [[HSL.download]]
    sha256 = "42bf303489cca221da7fb684447a2fef721b47b39e2d45a3a6e3d81ea42c724f"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.1+0/HSL.v4.0.1.x86_64-apple-darwin-libgfortran3.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "c7c6e8b5ef0899848f93cd54b28b6c45bf1a6a34"
libgfortran_version = "4.0.0"
os = "macos"

    [[HSL.download]]
    sha256 = "bc61211513235e9a266da72139c95133e52b1d7d681331acc9b050eaed5503df"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.1+0/HSL.v4.0.1.x86_64-apple-darwin-libgfortran4.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "05f4758d81ef71600d2aa3fe82960f5df9948f77"
libgfortran_version = "5.0.0"
os = "macos"

    [[HSL.download]]
    sha256 = "53c85df496e2dc79890310d711b1d88f9090317bc465829809deba11233b4bfb"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.1+0/HSL.v4.0.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "eeeb41c5adc199b523e6a5fa633aad2b18586b9c"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "004f33aa93fbf318fe26967f5550f6c7a3e9c68418a440fe9d1802d1ce5aa865"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.1+0/HSL.v4.0.1.x86_64-linux-gnu-libgfortran3.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "0ccf39ef9413ea372bee1007f838cb7af1a66944"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "f1edd9d680d905cab2edc0373b8c29ab63b33ba57c2f27899ce8789dbecc126b"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.1+0/HSL.v4.0.1.x86_64-linux-gnu-libgfortran4.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "45a19402a47964b26dccfe36409242db6c509c23"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "9e2364e8e5c95883cd51c2ccde21bbe9ceef8f9252c576ff946d6f94a0c69af8"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.1+0/HSL.v4.0.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "70f568a72f0a76d8787a057a07657e03918deaf3"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "f7c3169c9eb650e40b262600a2f199a672bd9b3fb92c742fbcf08f41d3ccf909"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.1+0/HSL.v4.0.1.x86_64-linux-musl-libgfortran3.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "23b2db8e299e25dd52ec232b158107becd61022f"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "2d867bb902d6c27417ffa816b02165129a4c8ebe53607e89e2410ed7488ce2dc"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.1+0/HSL.v4.0.1.x86_64-linux-musl-libgfortran4.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "214385723b27f12cbbe93d34ebb512141edee6d5"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[HSL.download]]
    sha256 = "9460e44e341476554aff64ec00fcf84a98ec3cc5e51e8ba8e615eabd7bd2e2ec"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.1+0/HSL.v4.0.1.x86_64-linux-musl-libgfortran5.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "5950af97ff9892def2c2661804975c74b6248afa"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[HSL.download]]
    sha256 = "1c8a9eea815fff19d93176488ec6a7cbe59399ecbc5eb7d6abee27d1bb188688"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.1+0/HSL.v4.0.1.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "e09e7a8e16d8f88da14ec2782bb8370ff0a338d1"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[HSL.download]]
    sha256 = "5ff32d2ba26846acbc58b54f928921c1cbb9d9af13a5ca30ab16d39ae07d28fe"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.1+0/HSL.v4.0.1.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "b0714ae47f95cdebb84a095693edecb588188a0a"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[HSL.download]]
    sha256 = "6f77376e26f71bc7faa7ce65bfa1777e9aa4501e6f556a7c547257429ff866f0"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.1+0/HSL.v4.0.1.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "af40c8c0608a4b02de965ad8f43bdc7b47bd938c"
libgfortran_version = "3.0.0"
os = "windows"

    [[HSL.download]]
    sha256 = "6fefe06905eb038e2d18cac261bc123da0a3c0527d16beb95d1c5183f9652be2"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.1+0/HSL.v4.0.1.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "589e40956bd690d7c6abef1975ed035db8db9a2a"
libgfortran_version = "4.0.0"
os = "windows"

    [[HSL.download]]
    sha256 = "e3ccaa2f4f41f307859c1e24ad11fe72cecd665baaf4c4bf42195de98e8d868b"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.1+0/HSL.v4.0.1.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "8d766cac1dbc32e82d075f592841f8063181552b"
libgfortran_version = "5.0.0"
os = "windows"

    [[HSL.download]]
    sha256 = "ebff5cf0763d983df8e2b3723e0bc4bdec1131efd56f6c08c034cccc43d1c486"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v4.0.1+0/HSL.v4.0.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
