[[HSL]]
arch = "aarch64"
git-tree-sha1 = "a8277b5bd7b199b2a4c71384be481e1a99d040d3"
os = "macos"

    [[HSL.download]]
    sha256 = "5d3fe537130ecf277bc05bf1bab8374ab8b292a97416ded073cb2bba2c299473"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v1.0.0+0/HSL.v1.0.0.aarch64-apple-darwin.tar.gz"
[[HSL]]
arch = "aarch64"
git-tree-sha1 = "185b1bb14efc38ee81ff9bb34c2a07410f6f8c13"
libc = "glibc"
os = "linux"

    [[HSL.download]]
    sha256 = "da48465d95c888812408cd0f873b6d382a20d037ecbc2615158c44ad6f2d7a68"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v1.0.0+0/HSL.v1.0.0.aarch64-linux-gnu.tar.gz"
[[HSL]]
arch = "aarch64"
git-tree-sha1 = "bd91dee063216f90cd3338f16f60103c3442a9d8"
libc = "musl"
os = "linux"

    [[HSL.download]]
    sha256 = "bfb5c106da4fd3136b389ef8a07fd0b9be3f200def79b07e888ea37b6da272de"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v1.0.0+0/HSL.v1.0.0.aarch64-linux-musl.tar.gz"
[[HSL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3b64a7deb26a9b7afe5ff84196e8835ed0c1d9b8"
libc = "glibc"
os = "linux"

    [[HSL.download]]
    sha256 = "b8008dd93b776e8c808632f00e0cd26e3a6b488c6a5a153fb6b06fc12f3e39ac"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v1.0.0+0/HSL.v1.0.0.armv6l-linux-gnueabihf.tar.gz"
[[HSL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e697f588476527c2153185db1bc59ad65efb6d46"
libc = "musl"
os = "linux"

    [[HSL.download]]
    sha256 = "6b27420651aa0524030e4e35de53edf7c32bf262d86ed627c4461ece657948be"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v1.0.0+0/HSL.v1.0.0.armv6l-linux-musleabihf.tar.gz"
[[HSL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "432f5b0e089648b1da991cba9722502c632be955"
libc = "glibc"
os = "linux"

    [[HSL.download]]
    sha256 = "beb56bd64f932d55c95268987ef394192f49cbcbc49eae720570f80b9cb018bb"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v1.0.0+0/HSL.v1.0.0.armv7l-linux-gnueabihf.tar.gz"
[[HSL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5c166ad40b3295aaec9de5771396138986f5085f"
libc = "musl"
os = "linux"

    [[HSL.download]]
    sha256 = "7ecad650f5e3ec0641ca44bf99cfefe25642acc2f4cdea00a6b7b3e76dd1bc03"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v1.0.0+0/HSL.v1.0.0.armv7l-linux-musleabihf.tar.gz"
[[HSL]]
arch = "i686"
git-tree-sha1 = "881253b20518d2e8f6981f04464a9b88f224ee18"
libc = "glibc"
os = "linux"

    [[HSL.download]]
    sha256 = "0e3292a2ab8185fd50928d06c871c2bee0974465b2c083e992ae92b2a8731215"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v1.0.0+0/HSL.v1.0.0.i686-linux-gnu.tar.gz"
[[HSL]]
arch = "i686"
git-tree-sha1 = "4cbfed48524044494f46b62619f0c8ddb0bc2fff"
libc = "musl"
os = "linux"

    [[HSL.download]]
    sha256 = "ac04912acc37355690ae7fceb66fb692a2947057f60e38e79508da1dad9c2e35"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v1.0.0+0/HSL.v1.0.0.i686-linux-musl.tar.gz"
[[HSL]]
arch = "i686"
git-tree-sha1 = "9759ed366d9064267e16397c112a013f4bf2d35a"
os = "windows"

    [[HSL.download]]
    sha256 = "5d3684df8136b40e6454366b4c694233276ef6a1e7d01e3f0cacbedd76fc74e5"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v1.0.0+0/HSL.v1.0.0.i686-w64-mingw32.tar.gz"
[[HSL]]
arch = "powerpc64le"
git-tree-sha1 = "2ff2046b0cf9788e61d6c06e404fb5876371539f"
libc = "glibc"
os = "linux"

    [[HSL.download]]
    sha256 = "dad378f85786ecff04e5d3991b369e73b4d8d317b95d7a9decdb01404937effb"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v1.0.0+0/HSL.v1.0.0.powerpc64le-linux-gnu.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "c2903ec4beda3049a51e07b29e851095c650bc5f"
os = "macos"

    [[HSL.download]]
    sha256 = "1ed7e768e6781b4bb75720360c75cf9b4551a449099dd4d1f8cef6fccf523d58"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v1.0.0+0/HSL.v1.0.0.x86_64-apple-darwin.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "ecece3e2c69a413a0e935cf52e03a3ad5492e137"
libc = "glibc"
os = "linux"

    [[HSL.download]]
    sha256 = "2c1bda38dcc5d2a2bba8db53cb677d5e403711a40c005f639480923cbd137c93"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v1.0.0+0/HSL.v1.0.0.x86_64-linux-gnu.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "3438ba7ff47dc4fca541e2d64d5027d1f05dda9a"
libc = "musl"
os = "linux"

    [[HSL.download]]
    sha256 = "d172ef029a1e3f22f16f8ec02a3abc90a34aff1bb44e1bb841cb303f9fa109b6"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v1.0.0+0/HSL.v1.0.0.x86_64-linux-musl.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "c8b8c3dc9e9d615787ff60caf8b5be8a199dc322"
os = "freebsd"

    [[HSL.download]]
    sha256 = "fb717b5f775902b4365a8ceea31f603d1c0a8739ca51867744831154f054b99f"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v1.0.0+0/HSL.v1.0.0.x86_64-unknown-freebsd.tar.gz"
[[HSL]]
arch = "x86_64"
git-tree-sha1 = "9f4db0ff6bb86eca80af47ee4025c8e402c5d3f4"
os = "windows"

    [[HSL.download]]
    sha256 = "77bf65e8040d063494bc91a83eb46f987fb275701b32b7dbf30ef2b12728c205"
    url = "https://github.com/JuliaBinaryWrappers/HSL_jll.jl/releases/download/HSL-v1.0.0+0/HSL.v1.0.0.x86_64-w64-mingw32.tar.gz"
